name: Export assets

on:
  workflow_dispatch:

permissions:
      contents: write 

env:
  INSTALL_RESOURCE: download
  PERSISTENT_STORE: ResourceTool/output/Unpack/CN
  
  UNPACK_FILE_DIRECTORY: ResourceTool/output/Unpack
  MANIFEST_VERSION_FILE: ResourceTool/output/Manifest/version.json

jobs:
  export-asset:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          
      - name: Restore cache (PersistentStore)
        uses: actions/cache/restore@v6
        with:
          path: ResourceTool/output
          key: ss-manifest-default
          restore-keys: ss-manifest-

      - name: Restore cache (InstallResource)
        uses: actions/cache/restore@v6
        with:
          path: download
          key: ss-install-resource-default
          restore-keys: ss-install-resource-

      - name: Run AssetStudioModCli
        id: run-asset-studio-tool
        working-directory: AssetStudioModCli
        run: |
          chmod +x ./AssetStudioModCLI
          EXPORT_DIR="${{ github.workspace }}/new-export"
          mkdir -p "$EXPORT_DIR"
          ./AssetStudioModCLI "${{ github.workspace }}/${{ env.PERSISTENT_STORE }}" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
          # ./AssetStudioModCLI "${{ github.workspace }}/${{ env.INSTALL_RESOURCE }}" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
        shell: bash

      - name: Sync new-export to export
        run: |
          mkdir -p export
          rsync -av "new-export/" "export/"
        shell: bash

      - name: Commit and push export/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add export

          VERSION_JSON="${{ env.MANIFEST_VERSION_FILE }}"
          if [ ! -f "$VERSION_JSON" ]; then
            echo "manifest version.json not found. skipping commit"
            exit 1
          fi
          GAME_VER=$(jq -r ".\"CN\".game_ver" "$VERSION_JSON")
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update $GAME_VER"
            git push
          fi
        shell: bash
      
