name: Export assets

on:
  workflow_dispatch:

permissions:
      contents: write 

env:
  INSTALL_RESOURCE: download
  PERSISTENT_STORE: ResourceTool/output/Unpack/CN
  
  UNPACK_FILE_DIRECTORY: ResourceTool/output/Unpack
  MANIFEST_VERSION_FILE: ResourceTool/output/Manifest/version.json

jobs:
  export-asset:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          
      - name: Restore cache (PersistentStore)
        uses: actions/cache/restore@v6
        with:
          path: ResourceTool/output
          key: ss-resource-default
          restore-keys: ss-resource-

      - name: Restore cache (old PersistentStore)
        uses: actions/cache/restore@v6
        with:
          path: diff-resource
          key: ss-diff-resource-default
          restore-keys: ss-diff-resource-

      - name: Run resource diff scripts
        id: run-resource-diff
        run: |
          DIR_A="diff-resource"
          DIR_B="${{ env.PERSISTENT_STORE }}"
          OUT_DIR="./diff_out"
          [ -d "$DIR_A" ] || mkdir -p "$DIR_A"
          node scripts/resource-diff.cjs -a "$DIR_A" -b "$DIR_B" -o "$OUT_DIR"

          if [ "$(ls -A "$OUT_DIR" 2>/dev/null)" ]; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "Resource diff output is empty, no update..."
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
  
      # - name: Restore cache (InstallResource)
      #   uses: actions/cache/restore@v6
      #   with:
      #     path: download
      #     key: ss-install-resource-default
      #     restore-keys: ss-install-resource-

      - name: Run AssetStudioModCli
        id: run-asset-studio-tool
        if: steps.run-resource-diff.outputs.updated == 'true'
        working-directory: AssetStudioModCli
        run: |
          chmod +x ./AssetStudioModCLI
          EXPORT_DIR="${{ github.workspace }}/new-export"
          mkdir -p "$EXPORT_DIR"
          ./AssetStudioModCLI "${{ github.workspace }}/diff_out" -t "tex2d" --image-format "webp" -o "$EXPORT_DIR"
          
          if [ "$(ls -A "$EXPORT_DIR" 2>/dev/null)" ]; then
            echo "AssetStudio output has files, updating status..."
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "AssetStudio output is empty, no update..."
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Sync diff file
        if: steps.run-resource-diff.outputs.updated == 'true'
        run: |
          DIR_A="diff-resource"
          OUT_DIR="./diff_out"
          echo "Resource diff output has files, updating cache dir..."
          rsync -a "$OUT_DIR/" "$DIR_A/"
        shell: bash

      - name: Save cache (old PersistentStore)
        if: steps.run-resource-diff.outputs.updated == 'true'
        uses: actions/cache/save@v6
        with:
          path: diff-resource
          key: ss-diff-resource-${{ github.run_id }}

      - name: Sync new-export to export
        if: steps.run-asset-studio-tool.outputs.updated == 'true'
        run: |
          mkdir -p export
          rsync -av --exclude='*#*' "new-export/" "export/"
        shell: bash

      - name: Commit and push export/
        if: steps.run-asset-studio-tool.outputs.updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add export

          VERSION_JSON="${{ env.MANIFEST_VERSION_FILE }}"
          if [ ! -f "$VERSION_JSON" ]; then
            echo "manifest version.json not found. skipping commit"
            exit 1
          fi
          GAME_VER=$(jq -r ".\"CN\".game_ver" "$VERSION_JSON")
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update $GAME_VER"
            git push
          fi
        shell: bash
      
      - name: Dispatch gen dating events data
        if: steps.run-asset-studio-tool.outputs.updated == 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
         token: ${{ secrets.GH_TOKEN }}
         repository: MakoStar/ss-dating
         event-type: asset-updated
         # client-payload: ${{ steps.commit-update-data.outputs.payload }}
