name: Refresh cache

on:
  workflow_dispatch:

env:
  CACHE_MANIFEST_DIR: ManifestTool/output
  RESTORE_MANIFEST_KEY_PREFIX: ss-resource-
  VERSION_JSON: ManifestTool/output/Manifest/version.json


jobs:
  refresh-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Restore resource cache
        id: restore-resource
        uses: actions/cache/restore@v6
        with:
          path: ResourceTool/output
          key: ss-resource-default
          restore-keys: ss-resource-
      
