name: Refresh cache

on:
  workflow_dispatch:

env:
  CACHE_MANIFEST_DIR: ManifestTool/output
  RESTORE_MANIFEST_KEY_PREFIX: ss-manifest-
  VERSION_JSON: ManifestTool/output/Manifest/version.json


jobs:
  refresh-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      # - name: Restore manifest cache
      #   id: restore-manifest
      #   uses: actions/cache/restore@v6
      #   with:
      #     path: "${{ env.CACHE_MANIFEST_DIR }}"
      #     key: "${{ env.RESTORE_MANIFEST_KEY_PREFIX }}default"
      #     restore-keys: "${{ env.RESTORE_MANIFEST_KEY_PREFIX }}"
      
